# Generated by Django 6.0.3 on 2026-03-15 04:14

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogindexpage_blogpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250, verbose_name='摘要')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='页面内容')),
            ],
            options={
                'verbose_name': '自定义页面',
                'verbose_name_plural': '自定义页面',
            },
            bases=('wagtailcore.page',),
        ),
    ]
